name: gis-tools
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - blosc=1.21.6=he440d0b_1
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py312h67db365_0
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.22.0=h4cfbee9_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cartopy=0.25.0=py312hf79963d_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py312h35888ee_1
  - cftime=1.6.4=py312h4f23490_2
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd9148b4_2
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cykhash=2.0.1=py312h30efb56_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cython=3.1.3=py312h7c45ced_2
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.16=py312h8285ef7_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py312h8a5da7c_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.16=hb03c661_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdal=3.12.0=py312hf50df08_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - geojson=3.2.0=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geos=3.14.1=h480dda7_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.11.11=py312ha08ed9d_0
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=he3c4edf_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=35_h59b9bed_openblas
  - libboost=1.88.0=hed09d94_3
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=35_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgdal-core=3.12.0=habacd5f_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=35_h7ac8fdf_openblas
  - liblapacke=3.9.0=35_he2f377e_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopencv=4.12.0=qt6_py312h31159dd_607
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - librttopo=1.1.0=h46dd2a8_20
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mapbox-vector-tile=2.2.0=pyhd8ed1ab_0
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.6=py312h7900ff3_1
  - matplotlib-base=3.10.6=py312he3d6523_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.10=h05a5f5f_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py312hf6400b3_104
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.2=py312h33ff503_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py312h7bb6282_607
  - openexr=3.4.3=he10986b_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.25.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - osmium-tool=1.18.0=hbe0e379_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py312hf79963d_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h0e488c8_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - proj=9.7.0=hb72c0af_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=6.31.1=py312hb8af0ac_2
  - psutil=7.0.0=py312h4c3975b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py312h598be00_607
  - pyclipper=1.3.0.post5=py312h30efb56_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.1=py312h053e1f3_2
  - pyparsing=3.2.3=pyhe01879c_2
  - pyproj=3.7.2=py312h9b6a7d9_2
  - pyrobuf=0.9.3=py312h1289d80_8
  - pyrosm=0.6.2=py312h30efb56_1
  - pyshp=3.0.1=pyhd8ed1ab_0
  - pyside6=6.9.3=py312h9da60e5_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.11=hd8ed1ab_0
  - python-rapidjson=1.21=py312h1289d80_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py312h4f23490_2
  - pyzmq=27.0.2=py312hfb55c3c_3
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-image=0.25.2=py312hf79963d_2
  - scikit-learn=1.7.1=py312h4f0b9e3_0
  - scipy=1.16.1=py312h7a1785b_1
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - shapely=2.1.2=py312h383787d_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.0=heff268d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.3.0=h8d10470_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py312h4c3975b_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h4c3975b_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2025.9.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.3.0=h988505b_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - zeromq=4.3.5=h3989a48_8
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.24.0=py312h3fa7853_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - affine==2.4.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - cattrs==25.2.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - lxml==6.0.1
      - osmium==4.1.1
      - pydap==3.5.6
      - rasterio==1.4.3
      - requests-cache==1.2.1
      - rioxarray==0.19.0
      - soupsieve==2.8
      - url-normalize==2.2.1
      - webob==1.8.9
prefix: /home/onav/miniforge3/envs/gis-tools
